---
swagger: "2.0"
info:
  description: "This is our BookToBook server"
  version: "1.0.0"
  title: "BookBook"
host: "booktobook.herokuapp.com"
basePath: "/api"
tags:
- name: "books"
  description: "Everything about Books"
schemes:
- "https"
- "http"
consumes:
- "applications/json"
produces:
- "applications/json"
paths:
  /book/{title}:
    get:
      tags:
      - "books"
      summary: "Find books by title"
      description: "Returns a list of books"
      operationId: "getBookByTitle"
      produces:
      - "application/json"
      parameters:
      - name: "title"
        in: "path"
        description: "title of book to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Book"
        400:
          description: "Invalid title supplied"
        404:
          description: "Book not found"
      x-swagger-router-controller: "Books"
definitions:
  Book:
    type: "object"
    properties:
      id:
        type: "string"
        example: "The BFG"
    xml:
      name: "Book"
    example:
      id: "The BFG"
